(cl:defpackage berry_pkg-msg
  (:use )
  (:export
   "<BERRYPOS>"
   "BERRYPOS"
   "<BERRYSETANGLE>"
   "BERRYSETANGLE"
   "<BERRYSETPOSITION>"
   "BERRYSETPOSITION"
   "<BULKSETITEM>"
   "BULKSETITEM"
   "<SETPOSITION>"
   "SETPOSITION"
   "<SYNCSETPOSITION>"
   "SYNCSETPOSITION"
  ))

