// Generated by gencpp from file berry_pkg/BerryKine.msg
// DO NOT EDIT!


#ifndef BERRY_PKG_MESSAGE_BERRYKINE_H
#define BERRY_PKG_MESSAGE_BERRYKINE_H

#include <ros/service_traits.h>


#include <berry_pkg/BerryKineRequest.h>
#include <berry_pkg/BerryKineResponse.h>


namespace berry_pkg
{

struct BerryKine
{

typedef BerryKineRequest Request;
typedef BerryKineResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BerryKine
} // namespace berry_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::berry_pkg::BerryKine > {
  static const char* value()
  {
    return "b7b8c1b034c1b069bff5d6c113f05355";
  }

  static const char* value(const ::berry_pkg::BerryKine&) { return value(); }
};

template<>
struct DataType< ::berry_pkg::BerryKine > {
  static const char* value()
  {
    return "berry_pkg/BerryKine";
  }

  static const char* value(const ::berry_pkg::BerryKine&) { return value(); }
};


// service_traits::MD5Sum< ::berry_pkg::BerryKineRequest> should match
// service_traits::MD5Sum< ::berry_pkg::BerryKine >
template<>
struct MD5Sum< ::berry_pkg::BerryKineRequest>
{
  static const char* value()
  {
    return MD5Sum< ::berry_pkg::BerryKine >::value();
  }
  static const char* value(const ::berry_pkg::BerryKineRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::berry_pkg::BerryKineRequest> should match
// service_traits::DataType< ::berry_pkg::BerryKine >
template<>
struct DataType< ::berry_pkg::BerryKineRequest>
{
  static const char* value()
  {
    return DataType< ::berry_pkg::BerryKine >::value();
  }
  static const char* value(const ::berry_pkg::BerryKineRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::berry_pkg::BerryKineResponse> should match
// service_traits::MD5Sum< ::berry_pkg::BerryKine >
template<>
struct MD5Sum< ::berry_pkg::BerryKineResponse>
{
  static const char* value()
  {
    return MD5Sum< ::berry_pkg::BerryKine >::value();
  }
  static const char* value(const ::berry_pkg::BerryKineResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::berry_pkg::BerryKineResponse> should match
// service_traits::DataType< ::berry_pkg::BerryKine >
template<>
struct DataType< ::berry_pkg::BerryKineResponse>
{
  static const char* value()
  {
    return DataType< ::berry_pkg::BerryKine >::value();
  }
  static const char* value(const ::berry_pkg::BerryKineResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BERRY_PKG_MESSAGE_BERRYKINE_H
