// Generated by gencpp from file berry_pkg/BerryGetPosition.msg
// DO NOT EDIT!


#ifndef BERRY_PKG_MESSAGE_BERRYGETPOSITION_H
#define BERRY_PKG_MESSAGE_BERRYGETPOSITION_H

#include <ros/service_traits.h>


#include <berry_pkg/BerryGetPositionRequest.h>
#include <berry_pkg/BerryGetPositionResponse.h>


namespace berry_pkg
{

struct BerryGetPosition
{

typedef BerryGetPositionRequest Request;
typedef BerryGetPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BerryGetPosition
} // namespace berry_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::berry_pkg::BerryGetPosition > {
  static const char* value()
  {
    return "b38e30458a843d420744e165c938e395";
  }

  static const char* value(const ::berry_pkg::BerryGetPosition&) { return value(); }
};

template<>
struct DataType< ::berry_pkg::BerryGetPosition > {
  static const char* value()
  {
    return "berry_pkg/BerryGetPosition";
  }

  static const char* value(const ::berry_pkg::BerryGetPosition&) { return value(); }
};


// service_traits::MD5Sum< ::berry_pkg::BerryGetPositionRequest> should match
// service_traits::MD5Sum< ::berry_pkg::BerryGetPosition >
template<>
struct MD5Sum< ::berry_pkg::BerryGetPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::berry_pkg::BerryGetPosition >::value();
  }
  static const char* value(const ::berry_pkg::BerryGetPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::berry_pkg::BerryGetPositionRequest> should match
// service_traits::DataType< ::berry_pkg::BerryGetPosition >
template<>
struct DataType< ::berry_pkg::BerryGetPositionRequest>
{
  static const char* value()
  {
    return DataType< ::berry_pkg::BerryGetPosition >::value();
  }
  static const char* value(const ::berry_pkg::BerryGetPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::berry_pkg::BerryGetPositionResponse> should match
// service_traits::MD5Sum< ::berry_pkg::BerryGetPosition >
template<>
struct MD5Sum< ::berry_pkg::BerryGetPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::berry_pkg::BerryGetPosition >::value();
  }
  static const char* value(const ::berry_pkg::BerryGetPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::berry_pkg::BerryGetPositionResponse> should match
// service_traits::DataType< ::berry_pkg::BerryGetPosition >
template<>
struct DataType< ::berry_pkg::BerryGetPositionResponse>
{
  static const char* value()
  {
    return DataType< ::berry_pkg::BerryGetPosition >::value();
  }
  static const char* value(const ::berry_pkg::BerryGetPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BERRY_PKG_MESSAGE_BERRYGETPOSITION_H
