// Generated by gencpp from file berry_pkg/BerryGetPositionRequest.msg
// DO NOT EDIT!


#ifndef BERRY_PKG_MESSAGE_BERRYGETPOSITIONREQUEST_H
#define BERRY_PKG_MESSAGE_BERRYGETPOSITIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace berry_pkg
{
template <class ContainerAllocator>
struct BerryGetPositionRequest_
{
  typedef BerryGetPositionRequest_<ContainerAllocator> Type;

  BerryGetPositionRequest_()
    : id1(0)
    , id2(0)
    , id3(0)
    , id4(0)  {
    }
  BerryGetPositionRequest_(const ContainerAllocator& _alloc)
    : id1(0)
    , id2(0)
    , id3(0)
    , id4(0)  {
  (void)_alloc;
    }



   typedef uint8_t _id1_type;
  _id1_type id1;

   typedef uint8_t _id2_type;
  _id2_type id2;

   typedef uint8_t _id3_type;
  _id3_type id3;

   typedef uint8_t _id4_type;
  _id4_type id4;





  typedef boost::shared_ptr< ::berry_pkg::BerryGetPositionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::berry_pkg::BerryGetPositionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct BerryGetPositionRequest_

typedef ::berry_pkg::BerryGetPositionRequest_<std::allocator<void> > BerryGetPositionRequest;

typedef boost::shared_ptr< ::berry_pkg::BerryGetPositionRequest > BerryGetPositionRequestPtr;
typedef boost::shared_ptr< ::berry_pkg::BerryGetPositionRequest const> BerryGetPositionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::berry_pkg::BerryGetPositionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::berry_pkg::BerryGetPositionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::berry_pkg::BerryGetPositionRequest_<ContainerAllocator1> & lhs, const ::berry_pkg::BerryGetPositionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id1 == rhs.id1 &&
    lhs.id2 == rhs.id2 &&
    lhs.id3 == rhs.id3 &&
    lhs.id4 == rhs.id4;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::berry_pkg::BerryGetPositionRequest_<ContainerAllocator1> & lhs, const ::berry_pkg::BerryGetPositionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace berry_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::berry_pkg::BerryGetPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::berry_pkg::BerryGetPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::berry_pkg::BerryGetPositionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::berry_pkg::BerryGetPositionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::berry_pkg::BerryGetPositionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::berry_pkg::BerryGetPositionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::berry_pkg::BerryGetPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "52e083e3b957566af167934660d2a43f";
  }

  static const char* value(const ::berry_pkg::BerryGetPositionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x52e083e3b957566aULL;
  static const uint64_t static_value2 = 0xf167934660d2a43fULL;
};

template<class ContainerAllocator>
struct DataType< ::berry_pkg::BerryGetPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "berry_pkg/BerryGetPositionRequest";
  }

  static const char* value(const ::berry_pkg::BerryGetPositionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::berry_pkg::BerryGetPositionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id1\n"
"uint8 id2\n"
"uint8 id3\n"
"uint8 id4\n"
;
  }

  static const char* value(const ::berry_pkg::BerryGetPositionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::berry_pkg::BerryGetPositionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id1);
      stream.next(m.id2);
      stream.next(m.id3);
      stream.next(m.id4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BerryGetPositionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::berry_pkg::BerryGetPositionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::berry_pkg::BerryGetPositionRequest_<ContainerAllocator>& v)
  {
    s << indent << "id1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id1);
    s << indent << "id2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id2);
    s << indent << "id3: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id3);
    s << indent << "id4: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BERRY_PKG_MESSAGE_BERRYGETPOSITIONREQUEST_H
