// Generated by gencpp from file berry_pkg/BerryGetPositionResponse.msg
// DO NOT EDIT!


#ifndef BERRY_PKG_MESSAGE_BERRYGETPOSITIONRESPONSE_H
#define BERRY_PKG_MESSAGE_BERRYGETPOSITIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace berry_pkg
{
template <class ContainerAllocator>
struct BerryGetPositionResponse_
{
  typedef BerryGetPositionResponse_<ContainerAllocator> Type;

  BerryGetPositionResponse_()
    : position1(0)
    , position2(0)
    , position3(0)
    , position4(0)  {
    }
  BerryGetPositionResponse_(const ContainerAllocator& _alloc)
    : position1(0)
    , position2(0)
    , position3(0)
    , position4(0)  {
  (void)_alloc;
    }



   typedef int32_t _position1_type;
  _position1_type position1;

   typedef int32_t _position2_type;
  _position2_type position2;

   typedef int32_t _position3_type;
  _position3_type position3;

   typedef int32_t _position4_type;
  _position4_type position4;





  typedef boost::shared_ptr< ::berry_pkg::BerryGetPositionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::berry_pkg::BerryGetPositionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BerryGetPositionResponse_

typedef ::berry_pkg::BerryGetPositionResponse_<std::allocator<void> > BerryGetPositionResponse;

typedef boost::shared_ptr< ::berry_pkg::BerryGetPositionResponse > BerryGetPositionResponsePtr;
typedef boost::shared_ptr< ::berry_pkg::BerryGetPositionResponse const> BerryGetPositionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::berry_pkg::BerryGetPositionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::berry_pkg::BerryGetPositionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::berry_pkg::BerryGetPositionResponse_<ContainerAllocator1> & lhs, const ::berry_pkg::BerryGetPositionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.position1 == rhs.position1 &&
    lhs.position2 == rhs.position2 &&
    lhs.position3 == rhs.position3 &&
    lhs.position4 == rhs.position4;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::berry_pkg::BerryGetPositionResponse_<ContainerAllocator1> & lhs, const ::berry_pkg::BerryGetPositionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace berry_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::berry_pkg::BerryGetPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::berry_pkg::BerryGetPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::berry_pkg::BerryGetPositionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::berry_pkg::BerryGetPositionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::berry_pkg::BerryGetPositionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::berry_pkg::BerryGetPositionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::berry_pkg::BerryGetPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6a81f06afdb51e739ccc838b6604a038";
  }

  static const char* value(const ::berry_pkg::BerryGetPositionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6a81f06afdb51e73ULL;
  static const uint64_t static_value2 = 0x9ccc838b6604a038ULL;
};

template<class ContainerAllocator>
struct DataType< ::berry_pkg::BerryGetPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "berry_pkg/BerryGetPositionResponse";
  }

  static const char* value(const ::berry_pkg::BerryGetPositionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::berry_pkg::BerryGetPositionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 position1\n"
"int32 position2\n"
"int32 position3\n"
"int32 position4\n"
;
  }

  static const char* value(const ::berry_pkg::BerryGetPositionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::berry_pkg::BerryGetPositionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position1);
      stream.next(m.position2);
      stream.next(m.position3);
      stream.next(m.position4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BerryGetPositionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::berry_pkg::BerryGetPositionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::berry_pkg::BerryGetPositionResponse_<ContainerAllocator>& v)
  {
    s << indent << "position1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position1);
    s << indent << "position2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position2);
    s << indent << "position3: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position3);
    s << indent << "position4: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BERRY_PKG_MESSAGE_BERRYGETPOSITIONRESPONSE_H
