// Generated by gencpp from file berry_pkg/BerryKineResponse.msg
// DO NOT EDIT!


#ifndef BERRY_PKG_MESSAGE_BERRYKINERESPONSE_H
#define BERRY_PKG_MESSAGE_BERRYKINERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace berry_pkg
{
template <class ContainerAllocator>
struct BerryKineResponse_
{
  typedef BerryKineResponse_<ContainerAllocator> Type;

  BerryKineResponse_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , a(0.0)  {
    }
  BerryKineResponse_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , a(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _a_type;
  _a_type a;





  typedef boost::shared_ptr< ::berry_pkg::BerryKineResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::berry_pkg::BerryKineResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BerryKineResponse_

typedef ::berry_pkg::BerryKineResponse_<std::allocator<void> > BerryKineResponse;

typedef boost::shared_ptr< ::berry_pkg::BerryKineResponse > BerryKineResponsePtr;
typedef boost::shared_ptr< ::berry_pkg::BerryKineResponse const> BerryKineResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::berry_pkg::BerryKineResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::berry_pkg::BerryKineResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::berry_pkg::BerryKineResponse_<ContainerAllocator1> & lhs, const ::berry_pkg::BerryKineResponse_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.a == rhs.a;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::berry_pkg::BerryKineResponse_<ContainerAllocator1> & lhs, const ::berry_pkg::BerryKineResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace berry_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::berry_pkg::BerryKineResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::berry_pkg::BerryKineResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::berry_pkg::BerryKineResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::berry_pkg::BerryKineResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::berry_pkg::BerryKineResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::berry_pkg::BerryKineResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::berry_pkg::BerryKineResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "048816fafbfc26a9b1dace8fa24075f0";
  }

  static const char* value(const ::berry_pkg::BerryKineResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x048816fafbfc26a9ULL;
  static const uint64_t static_value2 = 0xb1dace8fa24075f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::berry_pkg::BerryKineResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "berry_pkg/BerryKineResponse";
  }

  static const char* value(const ::berry_pkg::BerryKineResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::berry_pkg::BerryKineResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 a\n"
;
  }

  static const char* value(const ::berry_pkg::BerryKineResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::berry_pkg::BerryKineResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BerryKineResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::berry_pkg::BerryKineResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::berry_pkg::BerryKineResponse_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "a: ";
    Printer<float>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BERRY_PKG_MESSAGE_BERRYKINERESPONSE_H
