// Generated by gencpp from file berry_pkg/BulkGetItem.msg
// DO NOT EDIT!


#ifndef BERRY_PKG_MESSAGE_BULKGETITEM_H
#define BERRY_PKG_MESSAGE_BULKGETITEM_H

#include <ros/service_traits.h>


#include <berry_pkg/BulkGetItemRequest.h>
#include <berry_pkg/BulkGetItemResponse.h>


namespace berry_pkg
{

struct BulkGetItem
{

typedef BulkGetItemRequest Request;
typedef BulkGetItemResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BulkGetItem
} // namespace berry_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::berry_pkg::BulkGetItem > {
  static const char* value()
  {
    return "f0b74b4d53178e0d0ede26a30b687544";
  }

  static const char* value(const ::berry_pkg::BulkGetItem&) { return value(); }
};

template<>
struct DataType< ::berry_pkg::BulkGetItem > {
  static const char* value()
  {
    return "berry_pkg/BulkGetItem";
  }

  static const char* value(const ::berry_pkg::BulkGetItem&) { return value(); }
};


// service_traits::MD5Sum< ::berry_pkg::BulkGetItemRequest> should match
// service_traits::MD5Sum< ::berry_pkg::BulkGetItem >
template<>
struct MD5Sum< ::berry_pkg::BulkGetItemRequest>
{
  static const char* value()
  {
    return MD5Sum< ::berry_pkg::BulkGetItem >::value();
  }
  static const char* value(const ::berry_pkg::BulkGetItemRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::berry_pkg::BulkGetItemRequest> should match
// service_traits::DataType< ::berry_pkg::BulkGetItem >
template<>
struct DataType< ::berry_pkg::BulkGetItemRequest>
{
  static const char* value()
  {
    return DataType< ::berry_pkg::BulkGetItem >::value();
  }
  static const char* value(const ::berry_pkg::BulkGetItemRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::berry_pkg::BulkGetItemResponse> should match
// service_traits::MD5Sum< ::berry_pkg::BulkGetItem >
template<>
struct MD5Sum< ::berry_pkg::BulkGetItemResponse>
{
  static const char* value()
  {
    return MD5Sum< ::berry_pkg::BulkGetItem >::value();
  }
  static const char* value(const ::berry_pkg::BulkGetItemResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::berry_pkg::BulkGetItemResponse> should match
// service_traits::DataType< ::berry_pkg::BulkGetItem >
template<>
struct DataType< ::berry_pkg::BulkGetItemResponse>
{
  static const char* value()
  {
    return DataType< ::berry_pkg::BulkGetItem >::value();
  }
  static const char* value(const ::berry_pkg::BulkGetItemResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BERRY_PKG_MESSAGE_BULKGETITEM_H
