// Generated by gencpp from file berry_pkg/GetPosition.msg
// DO NOT EDIT!


#ifndef BERRY_PKG_MESSAGE_GETPOSITION_H
#define BERRY_PKG_MESSAGE_GETPOSITION_H

#include <ros/service_traits.h>


#include <berry_pkg/GetPositionRequest.h>
#include <berry_pkg/GetPositionResponse.h>


namespace berry_pkg
{

struct GetPosition
{

typedef GetPositionRequest Request;
typedef GetPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPosition
} // namespace berry_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::berry_pkg::GetPosition > {
  static const char* value()
  {
    return "b532ace3b383dc4c9e64687156423ac0";
  }

  static const char* value(const ::berry_pkg::GetPosition&) { return value(); }
};

template<>
struct DataType< ::berry_pkg::GetPosition > {
  static const char* value()
  {
    return "berry_pkg/GetPosition";
  }

  static const char* value(const ::berry_pkg::GetPosition&) { return value(); }
};


// service_traits::MD5Sum< ::berry_pkg::GetPositionRequest> should match
// service_traits::MD5Sum< ::berry_pkg::GetPosition >
template<>
struct MD5Sum< ::berry_pkg::GetPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::berry_pkg::GetPosition >::value();
  }
  static const char* value(const ::berry_pkg::GetPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::berry_pkg::GetPositionRequest> should match
// service_traits::DataType< ::berry_pkg::GetPosition >
template<>
struct DataType< ::berry_pkg::GetPositionRequest>
{
  static const char* value()
  {
    return DataType< ::berry_pkg::GetPosition >::value();
  }
  static const char* value(const ::berry_pkg::GetPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::berry_pkg::GetPositionResponse> should match
// service_traits::MD5Sum< ::berry_pkg::GetPosition >
template<>
struct MD5Sum< ::berry_pkg::GetPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::berry_pkg::GetPosition >::value();
  }
  static const char* value(const ::berry_pkg::GetPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::berry_pkg::GetPositionResponse> should match
// service_traits::DataType< ::berry_pkg::GetPosition >
template<>
struct DataType< ::berry_pkg::GetPositionResponse>
{
  static const char* value()
  {
    return DataType< ::berry_pkg::GetPosition >::value();
  }
  static const char* value(const ::berry_pkg::GetPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BERRY_PKG_MESSAGE_GETPOSITION_H
