// Generated by gencpp from file berry_pkg/SyncGetPosition.msg
// DO NOT EDIT!


#ifndef BERRY_PKG_MESSAGE_SYNCGETPOSITION_H
#define BERRY_PKG_MESSAGE_SYNCGETPOSITION_H

#include <ros/service_traits.h>


#include <berry_pkg/SyncGetPositionRequest.h>
#include <berry_pkg/SyncGetPositionResponse.h>


namespace berry_pkg
{

struct SyncGetPosition
{

typedef SyncGetPositionRequest Request;
typedef SyncGetPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SyncGetPosition
} // namespace berry_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::berry_pkg::SyncGetPosition > {
  static const char* value()
  {
    return "4a5a90af26ce6360c45e1980f134941b";
  }

  static const char* value(const ::berry_pkg::SyncGetPosition&) { return value(); }
};

template<>
struct DataType< ::berry_pkg::SyncGetPosition > {
  static const char* value()
  {
    return "berry_pkg/SyncGetPosition";
  }

  static const char* value(const ::berry_pkg::SyncGetPosition&) { return value(); }
};


// service_traits::MD5Sum< ::berry_pkg::SyncGetPositionRequest> should match
// service_traits::MD5Sum< ::berry_pkg::SyncGetPosition >
template<>
struct MD5Sum< ::berry_pkg::SyncGetPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::berry_pkg::SyncGetPosition >::value();
  }
  static const char* value(const ::berry_pkg::SyncGetPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::berry_pkg::SyncGetPositionRequest> should match
// service_traits::DataType< ::berry_pkg::SyncGetPosition >
template<>
struct DataType< ::berry_pkg::SyncGetPositionRequest>
{
  static const char* value()
  {
    return DataType< ::berry_pkg::SyncGetPosition >::value();
  }
  static const char* value(const ::berry_pkg::SyncGetPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::berry_pkg::SyncGetPositionResponse> should match
// service_traits::MD5Sum< ::berry_pkg::SyncGetPosition >
template<>
struct MD5Sum< ::berry_pkg::SyncGetPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::berry_pkg::SyncGetPosition >::value();
  }
  static const char* value(const ::berry_pkg::SyncGetPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::berry_pkg::SyncGetPositionResponse> should match
// service_traits::DataType< ::berry_pkg::SyncGetPosition >
template<>
struct DataType< ::berry_pkg::SyncGetPositionResponse>
{
  static const char* value()
  {
    return DataType< ::berry_pkg::SyncGetPosition >::value();
  }
  static const char* value(const ::berry_pkg::SyncGetPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BERRY_PKG_MESSAGE_SYNCGETPOSITION_H
