# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from berry_pkg/BerrySetAngle.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class BerrySetAngle(genpy.Message):
  _md5sum = "97b3b82c09f87a6730ecaae04f0b974e"
  _type = "berry_pkg/BerrySetAngle"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 th1
float32 th2
float32 th3
float32 th4
float32 angle1
float32 angle2
float32 angle3
float32 angle4
"""
  __slots__ = ['th1','th2','th3','th4','angle1','angle2','angle3','angle4']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       th1,th2,th3,th4,angle1,angle2,angle3,angle4

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BerrySetAngle, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.th1 is None:
        self.th1 = 0.
      if self.th2 is None:
        self.th2 = 0.
      if self.th3 is None:
        self.th3 = 0.
      if self.th4 is None:
        self.th4 = 0.
      if self.angle1 is None:
        self.angle1 = 0.
      if self.angle2 is None:
        self.angle2 = 0.
      if self.angle3 is None:
        self.angle3 = 0.
      if self.angle4 is None:
        self.angle4 = 0.
    else:
      self.th1 = 0.
      self.th2 = 0.
      self.th3 = 0.
      self.th4 = 0.
      self.angle1 = 0.
      self.angle2 = 0.
      self.angle3 = 0.
      self.angle4 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8f().pack(_x.th1, _x.th2, _x.th3, _x.th4, _x.angle1, _x.angle2, _x.angle3, _x.angle4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.th1, _x.th2, _x.th3, _x.th4, _x.angle1, _x.angle2, _x.angle3, _x.angle4,) = _get_struct_8f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8f().pack(_x.th1, _x.th2, _x.th3, _x.th4, _x.angle1, _x.angle2, _x.angle3, _x.angle4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.th1, _x.th2, _x.th3, _x.th4, _x.angle1, _x.angle2, _x.angle3, _x.angle4,) = _get_struct_8f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8f = None
def _get_struct_8f():
    global _struct_8f
    if _struct_8f is None:
        _struct_8f = struct.Struct("<8f")
    return _struct_8f
